# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: udaconnect.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10udaconnect.proto\"\x07\n\x05\x45mpty\"n\n\x0fLocationMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tperson_id\x18\x02 \x01(\x05\x12\x12\n\ncoordinate\x18\x03 \x01(\t\x12\x15\n\rcreation_time\x18\x04 \x01(\t\x12\x11\n\twkt_shape\x18\x05 \x01(\t\"\x1d\n\x0fLocationRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"X\n\rPersonMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x04 \x01(\t\"4\n\x11PersonMessageList\x12\x1f\n\x07persons\x18\x01 \x03(\x0b\x32\x0e.PersonMessage\"\x1b\n\rPersonRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"W\n\x11\x43onnectionMessage\x12\"\n\x08location\x18\x01 \x01(\x0b\x32\x10.LocationMessage\x12\x1e\n\x06person\x18\x02 \x01(\x0b\x32\x0e.PersonMessage\"A\n\x16\x43onnectionsMessageList\x12\'\n\x0b\x63onnections\x18\x01 \x03(\x0b\x32\x12.ConnectionMessage\"W\n\x11\x43onnectionRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nstart_date\x18\x02 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x03 \x01(\t\x12\x10\n\x08\x64istance\x18\x04 \x01(\t2A\n\x0fLocationService\x12.\n\x08Retrieve\x12\x10.LocationRequest\x1a\x10.LocationMessage2\x90\x01\n\rPersonService\x12(\n\x06\x43reate\x12\x0e.PersonMessage\x1a\x0e.PersonMessage\x12*\n\x08Retrieve\x12\x0e.PersonRequest\x1a\x0e.PersonMessage\x12)\n\x0bRetrieveAll\x12\x06.Empty\x1a\x12.PersonMessageList2P\n\x11\x43onnectionService\x12;\n\x0c\x46indContacts\x12\x12.ConnectionRequest\x1a\x17.ConnectionsMessageListb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'udaconnect_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=20
  _EMPTY._serialized_end=27
  _LOCATIONMESSAGE._serialized_start=29
  _LOCATIONMESSAGE._serialized_end=139
  _LOCATIONREQUEST._serialized_start=141
  _LOCATIONREQUEST._serialized_end=170
  _PERSONMESSAGE._serialized_start=172
  _PERSONMESSAGE._serialized_end=260
  _PERSONMESSAGELIST._serialized_start=262
  _PERSONMESSAGELIST._serialized_end=314
  _PERSONREQUEST._serialized_start=316
  _PERSONREQUEST._serialized_end=343
  _CONNECTIONMESSAGE._serialized_start=345
  _CONNECTIONMESSAGE._serialized_end=432
  _CONNECTIONSMESSAGELIST._serialized_start=434
  _CONNECTIONSMESSAGELIST._serialized_end=499
  _CONNECTIONREQUEST._serialized_start=501
  _CONNECTIONREQUEST._serialized_end=588
  _LOCATIONSERVICE._serialized_start=590
  _LOCATIONSERVICE._serialized_end=655
  _PERSONSERVICE._serialized_start=658
  _PERSONSERVICE._serialized_end=802
  _CONNECTIONSERVICE._serialized_start=804
  _CONNECTIONSERVICE._serialized_end=884
# @@protoc_insertion_point(module_scope)
